CREATE TABLE company (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE TABLE project (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE TABLE company_project_mapping (
    company_id INTEGER NOT NULL,
    project_id INTEGER NOT NULL,
    PRIMARY KEY (company_id,project_id)
);

ALTER TABLE IF EXISTS company_project_mapping
ADD CONSTRAINT company_id_fk FOREIGN KEY (company_id) REFERENCES company;

ALTER TABLE IF EXISTS company_project_mapping
ADD CONSTRAINT project_id_fk FOREIGN KEY (project_id) REFERENCES project;